name = "Dimension"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "A port of HTML5UP's dimension theme, optimized for markdown based CMS."
homepage = "https://github.com/TheFenrisLycaon/dimension/"
tags = ["blog", "clean", "customizable", "dark", "highlighting", "minimal", "personal", "responsive", "simple"]
features = ["blog", "syntax highlighting"]
min_version = 0.54

[author]
  name = "Fenris Lycaon"
  homepage = "https://thefenrislycaon.github.io"
